//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgvClientWPF.AgvTrayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgvTrayService.ITrayService")]
    public interface ITrayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrayService/GetTrayListByDeliveryNr", ReplyAction="http://tempuri.org/ITrayService/GetTrayListByDeliveryNrResponse")]
        AGVCenterLib.Model.ViewModel.TrayDeliveryViewModel[] GetTrayListByDeliveryNr(string deliveryNr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrayServiceChannel : AgvClientWPF.AgvTrayService.ITrayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrayServiceClient : System.ServiceModel.ClientBase<AgvClientWPF.AgvTrayService.ITrayService>, AgvClientWPF.AgvTrayService.ITrayService {
        
        public TrayServiceClient() {
        }
        
        public TrayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AGVCenterLib.Model.ViewModel.TrayDeliveryViewModel[] GetTrayListByDeliveryNr(string deliveryNr) {
            return base.Channel.GetTrayListByDeliveryNr(deliveryNr);
        }
    }
}
