//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgvClientWPF.AgvSystemService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgvSystemService.ISystemService")]
    public interface ISystemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemService/GetListGreaterThan", ReplyAction="http://tempuri.org/ISystemService/GetListGreaterThanResponse")]
        AGVCenterLib.Model.ViewModel.MoveTaskScheduleModel[] GetListGreaterThan(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemService/GetListGreaterThan", ReplyAction="http://tempuri.org/ISystemService/GetListGreaterThanResponse")]
        System.Threading.Tasks.Task<AGVCenterLib.Model.ViewModel.MoveTaskScheduleModel[]> GetListGreaterThanAsync(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemService/CreateMoveTaskSchdule", ReplyAction="http://tempuri.org/ISystemService/CreateMoveTaskSchduleResponse")]
        AGVCenterLib.Model.Message.ResultMessage CreateMoveTaskSchdule(AGVCenterLib.Model.ViewModel.MoveTaskScheduleModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemService/CreateMoveTaskSchdule", ReplyAction="http://tempuri.org/ISystemService/CreateMoveTaskSchduleResponse")]
        System.Threading.Tasks.Task<AGVCenterLib.Model.Message.ResultMessage> CreateMoveTaskSchduleAsync(AGVCenterLib.Model.ViewModel.MoveTaskScheduleModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemService/DeleteMoveTaskSchedule", ReplyAction="http://tempuri.org/ISystemService/DeleteMoveTaskScheduleResponse")]
        AGVCenterLib.Model.Message.ResultMessage DeleteMoveTaskSchedule(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemService/DeleteMoveTaskSchedule", ReplyAction="http://tempuri.org/ISystemService/DeleteMoveTaskScheduleResponse")]
        System.Threading.Tasks.Task<AGVCenterLib.Model.Message.ResultMessage> DeleteMoveTaskScheduleAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemServiceChannel : AgvClientWPF.AgvSystemService.ISystemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemServiceClient : System.ServiceModel.ClientBase<AgvClientWPF.AgvSystemService.ISystemService>, AgvClientWPF.AgvSystemService.ISystemService {
        
        public SystemServiceClient() {
        }
        
        public SystemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AGVCenterLib.Model.ViewModel.MoveTaskScheduleModel[] GetListGreaterThan(System.DateTime dateTime) {
            return base.Channel.GetListGreaterThan(dateTime);
        }
        
        public System.Threading.Tasks.Task<AGVCenterLib.Model.ViewModel.MoveTaskScheduleModel[]> GetListGreaterThanAsync(System.DateTime dateTime) {
            return base.Channel.GetListGreaterThanAsync(dateTime);
        }
        
        public AGVCenterLib.Model.Message.ResultMessage CreateMoveTaskSchdule(AGVCenterLib.Model.ViewModel.MoveTaskScheduleModel model) {
            return base.Channel.CreateMoveTaskSchdule(model);
        }
        
        public System.Threading.Tasks.Task<AGVCenterLib.Model.Message.ResultMessage> CreateMoveTaskSchduleAsync(AGVCenterLib.Model.ViewModel.MoveTaskScheduleModel model) {
            return base.Channel.CreateMoveTaskSchduleAsync(model);
        }
        
        public AGVCenterLib.Model.Message.ResultMessage DeleteMoveTaskSchedule(int id) {
            return base.Channel.DeleteMoveTaskSchedule(id);
        }
        
        public System.Threading.Tasks.Task<AGVCenterLib.Model.Message.ResultMessage> DeleteMoveTaskScheduleAsync(int id) {
            return base.Channel.DeleteMoveTaskScheduleAsync(id);
        }
    }
}
