//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgvClientWPF.AgvProductService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgvProductService.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateUniqItem", ReplyAction="http://tempuri.org/IProductService/CreateUniqItemResponse")]
        AGVCenterLib.Model.Message.ResultMessage CreateUniqItem(AGVCenterLib.Model.ViewModel.UniqueItemModel item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindUniqItemByNr", ReplyAction="http://tempuri.org/IProductService/FindUniqItemByNrResponse")]
        AGVCenterLib.Model.ViewModel.UniqueItemModel FindUniqItemByNr(string nr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : AgvClientWPF.AgvProductService.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<AgvClientWPF.AgvProductService.IProductService>, AgvClientWPF.AgvProductService.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AGVCenterLib.Model.Message.ResultMessage CreateUniqItem(AGVCenterLib.Model.ViewModel.UniqueItemModel item) {
            return base.Channel.CreateUniqItem(item);
        }
        
        public AGVCenterLib.Model.ViewModel.UniqueItemModel FindUniqItemByNr(string nr) {
            return base.Channel.FindUniqItemByNr(nr);
        }
    }
}
